name: ACARS Router
version: "0.1.1"
slug: acars_router
description: Routes VDLM2 messages from the NUT Pi to ACARS Hub and Airframes
url: "https://github.com/swise01/HA-NWR-SDR/tree/main/acars_router"
arch:
  - amd64
startup: services
boot: auto
init: false
ports:
  5555/udp: 5555
ports_description:
  5555/udp: VDLM2 JSON input from NUT Pi dumpvdl2
